name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we want to test our package on several versions of Python
        python-version: [3.8, 3.9]
    steps:
      steps:
  - name: Test & publish code coverage
    uses: paambaati/codeclimate-action@v5.0.0
    env:
      CC_TEST_REPORTER_ID:${{ secrets.CC_TEST_REPORTER_ID }}
      with:
      coverageCommand: poetry run test-coverage
      debug: true
